### ISSUE TITLE
How to use the example under vue or ES6 module？

### ISSUE THREAD

**Issue by hahaxiaowai** [fcor/arjs-gestures#11]
Hi! 
I want to use this demo in a modular form, but neither AR.js nor Aframe.js has a modular demo. How can i do it?

**Comment by fcor** [comment]
Hi! Sorry for my late response, Right now AR.js does not support modules but it will be possible soon! once it's done I will update this tool to make it easier to implement that way.

**Comment by hahaxiaowai** [comment]
oh.Thank you for your reply and look forward to your updates.I will close this issues
